### ISSUE TITLE
Server Error when Installed on Frappecloud

### ISSUE THREAD

**Issue by zuron7** [frappe/chat#16]
Hi There, 

I installed this app on Frappecloud on v13 and it seems to throw a server error. Just thought I'd put it here. I'm using the following apps and version numbers.

![image](https://user-images.githubusercontent.com/7473369/140296920-17950b1b-62d4-4644-a8a3-e23b7b822c4e.png)

Will try with a fresh install and let you know if I'm facing the same issues.

**Comment by chrisdent** [comment]
Same happen to me.

Shows this error:

AttributeError: type object 'datetime.time' has no attribute 'fromisoformat'

**Comment by codescientist703** [comment]
@chrisdent you can fix the error by upgrading your python version to 3.7.
