### ISSUE TITLE
AttributeError: type object 'datetime.time' has no attribute 'fromisoformat'

### ISSUE THREAD

**Issue by fkalpana** [frappe/chat#17]
Chat settings - > Enable chat  - > Save 
Error "AttributeError: type object 'datetime.time' has no attribute 'fromisoformat' " 

This happened after moving ERPNext from one server to other, and re-installing Chat app.

**Comment by codescientist703** [comment]
see this https://github.com/frappe/chat/issues/6

**Comment by dendysaleh** [comment]
AttributeError: type object 'datetime.time' has no attribute 'fromisoformat'

You should upgrade your Frappe with Python 3.7+, do on your Development server... when success... back to original code.

On your Production server that still on Python 3.6 you can do the trick:

/home/frappe/frappe-bench/apps/chat/chat/utils/__init__.py

# at row #5 add this:
from datetime import date
from datetime import datetime
import dateutil
from dateutil import parser

# at row #102 add this:
        #start_time = datetime.time.fromisoformat(chat_settings.start_time)
        start_time = dateutil.parser.parse(chat_settings.start_time)
        #end_time = datetime.time.fromisoformat(chat_settings.end_time)
        end_time = dateutil.parser.parse(chat_settings.end_time)
        #current_time = datetime.datetime.now().time()
        today = date.today()
        iso_date = today.isoformat()
        current_time = dateutil.parser.parse(iso_date)

-------------
# adjust server time with your country zone and
# restart all stuffs at command line

frappe@ubuntu:~$ date
Wed Nov 23 08:46:46 UTC 2022
frappe@ubuntu:~$ sudo mv /etc/localtime /etc/localtime.orig
frappe@ubuntu:~$ sudo ln -sf /usr/share/zoneinfo/Asia/Jakarta /etc/localtime
frappe@ubuntu:~$ date
Wed Nov 23 15:49:26 WIB 2022
frappe@ubuntu:~$ sudo supervisorctl restart all
frappe-bench-workers:frappe-bench-frappe-schedule: stopped
frappe-bench-web:frappe-bench-node-socketio: stopped
frappe-bench-redis:frappe-bench-redis-queue: stopped
frappe-bench-redis:frappe-bench-redis-cache: stopped
frappe-bench-redis:frappe-bench-redis-socketio: stopped
frappe-bench-workers:frappe-bench-frappe-default-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-long-worker-0: stopped
frappe-bench-workers:frappe-bench-frappe-short-worker-0: stopped
frappe-bench-web:frappe-bench-frappe-web: stopped
frappe-bench-workers:frappe-bench-frappe-schedule: started
frappe-bench-workers:frappe-bench-frappe-default-worker-0: started
frappe-bench-workers:frappe-bench-frappe-long-worker-0: started
frappe-bench-workers:frappe-bench-frappe-short-worker-0: started
frappe-bench-web:frappe-bench-frappe-web: started
frappe-bench-web:frappe-bench-node-socketio: started
frappe-bench-redis:frappe-bench-redis-queue: started
frappe-bench-redis:frappe-bench-redis-cache: started
frappe-bench-redis:frappe-bench-redis-socketio: started
frappe@ubuntu:~$

Its work for me...

Installed Apps
Frappe Chat: v0.0.1 (main)
ERPNext: v13.40.3 (version-13)
Frappe Framework: v13.42.0 (version-13)

Salam dari Blok Wage Pasaleman Cirebon West Java… :)…
