### ISSUE TITLE
Dark mode not correctly supported

### ISSUE THREAD

**Issue by blewsky** [frappe/chat#20]
See image:
![image](https://user-images.githubusercontent.com/87971956/143963128-e5252c4a-c368-49b1-8e33-4cc636f5389f.png)

Frappe Chat: v0.0.1 (HEAD)
ERPNext: v13.14.1 (version-13)
Frappe Framework: v13.14.1 (HEAD)

**Comment by codescientist703** [comment]
Dark mode is now added

![Screenshot from 2021-12-07 13-44-54](https://user-images.githubusercontent.com/44427574/144991555-59edf760-db59-4ae2-a070-a466c5abfab2.png)
