### ISSUE TITLE
Missing notification

### ISSUE THREAD

**Issue by rioshaz** [frappe/chat#22]
Guys any news on how to implement the notifications and how to gt notifications on mobile app or browser ?

**Comment by codescientist703** [comment]
There is already sound-based notification system implemented

**Comment by rioshaz** [comment]
@codescientist703 sound only comes when chat is open.. it doesnt make sound if the chat window is closed..
i have to keep chat windows open always for sound to come.. .

**Comment by rioshaz** [comment]
@codescientist703  i have updated to latest erp n frappe version

the setting icon is gone n all user images have reset and now displays the same user,,pls fix.. before it was fine..

<img width="425" alt="image" src="https://user-images.githubusercontent.com/54880467/145582006-54348da0-2c1b-4e60-8211-ca0c06aa0fb3.png">

shall i update to latest chat version too ?

**Comment by rioshaz** [comment]
ok i fixed it ... thanks 

i agree sound comes but if u are away n come to work... u wouldnt know a chat has come as long as there isnt any kind of visual hint.. like may be a chat counts on the chat icon. in red color... 

group works  but i cant see who all are in the group or how do i add more people to it or remove ..
 
also there is always a green dot next to anyone u chat to,, even when he/she is offline.. i guess this is bug.. 
also pls add chat forward n reply option....

thanks for ur good work bussy..
