### ISSUE TITLE
Bug - latest chat msgs dont come on top..

### ISSUE THREAD

**Issue by rioshaz** [frappe/chat#25]
latest messages don't come at the top when viewing all chats list.  i have to manually reload then only the latest chat get to top..
pls fix buddy..

also usr online/offline status not shown in chat list..

**Comment by codescientist703** [comment]
There is no way to know whether the user is online or offline. I will implement that feature when it is implemented in the framework.

**Comment by rioshaz** [comment]
i think this feature is there bcoz in older verison V12 u could see list of online users in chat.. so pls look if u dont mind.
also based in access logs also this can be done..
