### ISSUE TITLE
how to mak a system notification for unread chat

### ISSUE THREAD

**Issue by rioshaz** [frappe/chat#27]
how to send a system notifications he chat is unread:  what condition to use..

<img width="880" alt="image" src="https://user-images.githubusercontent.com/54880467/146936285-d6d5de11-bf6f-4a6e-8908-23bd4ddfcaa7.png">

if we can have a field in chat message doctype of unread n unread  and receiver ... this can be done. 
pls advice....

**Comment by codescientist703** [comment]
Do not spam by creating unnecessary issues like this. If you want to request a new feature do it in a single issue. Now onwards any issue like this will be closed.
