### ISSUE TITLE
build.json - chat folder

### ISSUE THREAD

**Issue by guilmori** [frappe/chat#5]
Please remove the chat/ folder from the build.json.

Since the folder is symlinked within the asset folder, the bundled files are visible within the app/public/ folder, and when we search within the app, results are duplicated between 'real' and 'bundle' file.
![image](https://user-images.githubusercontent.com/9451512/136478666-12153670-cdfc-442d-83b8-4ae166e80cdb.png)

Also the bundled file messes with git status:

![image](https://user-images.githubusercontent.com/9451512/136478960-a56fdc06-e950-4487-bee8-5bdb1b112df6.png)

**Comment by codescientist703** [comment]
Fixed in this [commit](https://github.com/frappe/chat/commit/ee2476671b8d794c1b7720bb1c33b648d4fe6ff7).
